alias date='date +%Y-%m-%d-%H-%M-%S'

#shortkey-->directory
alias data='cd /media/cani_ic/Data'
alias video='cd /media/cani_ic/Data/video'
alias music='cd /media/cani_ic/Data/music'
alias home='cd /home/cani_ic'
alias down='cd /home/cani_ic/Downloads'

#cmd
alias win7='cd /home/cani_ic/vmware/win7;vmware -X win7.vmx &'
alias linuxprobe='cd /home/cani_ic/vmware/linux_probe;vmware -X linux_probe.vmx & '
alias bgm='rhythmbox /home/cani_ic/Music/softmusic.mp3 &'
alias grep='grep -nr'
alias gerp='grep'
alias sdn='shutdown now'
alias ebashrc='vi ~/.bashrc'
alias vbashrc='. ~/.bashrc'
alias ls='clear;ls --color=auto -l'
alias la='ls -al'

#git
alias gsts='git status'
alias glog='git log' 
alias grmv='git rm' 
alias gcmt='git commit'
alias gadd='git add'
